### ISSUE TITLE
Add support for chain simulation

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#210]
## Description

Add support for emulating testnet and mainnet networks, using `--chain-id` emulator flag.

## TODO

- [ ] Fix account index lookup (use the correct chain ID)
- [ ] Fix default account indexing (generate default accounts using index lookup and the correct chain ID)
- [ ] Optionally support `--start-block-height` flag
